# Supported: GCC, CLANG, ICX
TAG ?= ICX
ENABLE_MPI ?= true
ENABLE_OPENMP ?= false

#Feature options
OPTIONS +=  -DARRAY_ALIGNMENT=64
OPTIONS +=  -DVERBOSE
#OPTIONS +=  -DDEBUG
#OPTIONS +=  -DBOUNDCHECK
#OPTIONS +=  -DVERBOSE_AFFINITY
#OPTIONS +=  -DVERBOSE_DATASIZE
#OPTIONS +=  -DVERBOSE_TIMER
